import { MigrationInterface, QueryRunner } from "typeorm";

export class SeedCity1724232237552 implements MigrationInterface {
    name = 'Seed1724232237552'

    public async up(queryRunner: QueryRunner): Promise<void> {
       await queryRunner.query(`
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1, 'اسکو', 'اسکو', 1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (2,'اهر','اهر',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (3,'ایلخچی','ایلخچی',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (4,'آبش احمد','آبش-احمد',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (5,'آذرشهر','آذرشهر',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (6,'آقکند','آقکند',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (7,'باسمنج','باسمنج',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (8,'بخشایش','بخشایش',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (9,'بستان آباد','بستان-آباد',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (10,'بناب','بناب',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (11,'بناب جدید','بناب-جدید',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (12,'تبریز','تبریز',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (13,'ترک','ترک',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (14,'ترکمانچای','ترکمانچای',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (15,'تسوج','تسوج',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (16,'تیکمه داش','تیکمه-داش',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (17,'جلفا','جلفا',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (18,'خاروانا','خاروانا',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (19,'خامنه','خامنه',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (20,'خراجو','خراجو',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (21,'خسروشهر','خسروشهر',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (22,'خضرلو','خضرلو',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (23,'خمارلو','خمارلو',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (24,'خواجه','خواجه',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (25,'دوزدوزان','دوزدوزان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (26,'زرنق','زرنق',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (27,'زنوز','زنوز',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (28,'سراب','سراب',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (29,'سردرود','سردرود',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (30,'سهند','سهند',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (31,'سیس','سیس',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (32,'سیه رود','سیه-رود',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (33,'شبستر','شبستر',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (34,'شربیان','شربیان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (35,'شرفخانه','شرفخانه',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (36,'شندآباد','شندآباد',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (37,'صوفیان','صوفیان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (38,'عجب شیر','عجب-شیر',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (39,'قره آغاج','قره-آغاج',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (40,'کشکسرای','کشکسرای',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (41,'کلوانق','کلوانق',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (42,'کلیبر','کلیبر',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (43,'کوزه کنان','کوزه-کنان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (44,'گوگان','گوگان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (45,'لیلان','لیلان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (46,'مراغه','مراغه',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (47,'مرند','مرند',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (48,'ملکان','ملکان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (49,'ملک کیان','ملک-کیان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (50,'ممقان','ممقان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (51,'مهربان','مهربان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (52,'میانه','میانه',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (53,'نظرکهریزی','نظرکهریزی',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (54,'هادی شهر','هادی-شهر',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (55,'هرگلان','هرگلان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (56,'هریس','هریس',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (57,'هشترود','هشترود',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (58,'هوراند','هوراند',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (59,'وایقان','وایقان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (60,'ورزقان','ورزقان',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (61,'یامچی','یامچی',1);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (62,'ارومیه','ارومیه',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (63,'اشنویه','اشنویه',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (64,'ایواوغلی','ایواوغلی',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (65,'آواجیق','آواجیق',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (66,'باروق','باروق',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (67,'بازرگان','بازرگان',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (68,'بوکان','بوکان',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (69,'پلدشت','پلدشت',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (70,'پیرانشهر','پیرانشهر',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (71,'تازه شهر','تازه-شهر',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (72,'تکاب','تکاب',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (73,'چهاربرج','چهاربرج',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (74,'خوی','خوی',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (75,'دیزج دیز','دیزج-دیز',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (76,'ربط','ربط',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (77,'سردشت','آذربایجان-غربی-سردشت',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (78,'سرو','سرو',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (79,'سلماس','سلماس',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (80,'سیلوانه','سیلوانه',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (81,'سیمینه','سیمینه',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (82,'سیه چشمه','سیه-چشمه',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (83,'شاهین دژ','شاهین-دژ',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (84,'شوط','شوط',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (85,'فیرورق','فیرورق',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (86,'قره ضیاءالدین','قره-ضیاءالدین',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (87,'قطور','قطور',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (88,'قوشچی','قوشچی',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (89,'کشاورز','کشاورز',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (90,'گردکشانه','گردکشانه',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (91,'ماکو','ماکو',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (92,'محمدیار','محمدیار',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (93,'محمودآباد','آذربایجان-غربی-محمودآباد',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (94,'مهاباد','آذربایجان-غربی-مهاباد',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (95,'میاندوآب','میاندوآب',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (96,'میرآباد','میرآباد',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (97,'نالوس','نالوس',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (98,'نقده','نقده',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (99,'نوشین','نوشین',2);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (100,'اردبیل','اردبیل',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (101,'اصلاندوز','اصلاندوز',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (102,'آبی بیگلو','آبی-بیگلو',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (103,'بیله سوار','بیله-سوار',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (104,'پارس آباد','پارس-آباد',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (105,'تازه کند','تازه-کند',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (106,'تازه کندانگوت','تازه-کندانگوت',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (107,'جعفرآباد','جعفرآباد',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (108,'خلخال','خلخال',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (109,'رضی','رضی',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (110,'سرعین','سرعین',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (111,'عنبران','عنبران',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (112,'فخرآباد','فخرآباد',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (113,'کلور','کلور',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (114,'کوراییم','کوراییم',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (115,'گرمی','گرمی',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (116,'گیوی','گیوی',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (117,'لاهرود','لاهرود',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (118,'مشگین شهر','مشگین-شهر',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (119,'نمین','نمین',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (120,'نیر','اردبیل-نیر',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (121,'هشتجین','هشتجین',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (122,'هیر','هیر',3);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (123,'ابریشم','ابریشم',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (124,'ابوزیدآباد','ابوزیدآباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (125,'اردستان','اردستان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (126,'اژیه','اژیه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (127,'اصفهان','اصفهان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (128,'افوس','افوس',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (129,'انارک','انارک',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (130,'ایمانشهر','ایمانشهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (131,'آران وبیدگل','آران-وبیدگل',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (132,'بادرود','بادرود',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (133,'باغ بهادران','باغ-بهادران',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (134,'بافران','بافران',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (135,'برزک','برزک',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (136,'برف انبار','برف-انبار',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (137,'بهاران شهر','بهاران-شهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (138,'بهارستان','بهارستان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (139,'بوئین و میاندشت','بوئین-میاندشت',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (140,'پیربکران','پیربکران',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (141,'تودشک','تودشک',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (142,'تیران','تیران',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (143,'جندق','جندق',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (144,'جوزدان','جوزدان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (145,'جوشقان و کامو','جوشقان-کامو',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (146,'چادگان','چادگان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (147,'چرمهین','چرمهین',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (148,'چمگردان','چمگردان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (149,'حبیب آباد','حبیب-آباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (150,'حسن آباد','اصفهان-حسن-آباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (151,'حنا','حنا',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (152,'خالدآباد','خالدآباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (153,'خمینی شهر','خمینی-شهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (154,'خوانسار','خوانسار',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (155,'خور','اصفهان-خور',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (157,'خورزوق','خورزوق',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (158,'داران','داران',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (159,'دامنه','دامنه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (160,'درچه','درچه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (161,'دستگرد','دستگرد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (162,'دهاقان','دهاقان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (163,'دهق','دهق',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (164,'دولت آباد','اصفهان-دولت-آباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (165,'دیزیچه','دیزیچه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (166,'رزوه','رزوه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (167,'رضوانشهر','اصفهان-رضوانشهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (168,'زاینده رود','زاینده-رود',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (169,'زرین شهر','زرین-شهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (170,'زواره','زواره',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (171,'زیباشهر','زیباشهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (172,'سده لنجان','سده-لنجان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (173,'سفیدشهر','سفیدشهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (174,'سگزی','سگزی',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (175,'سمیرم','سمیرم',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (176,'شاهین شهر','شاهین-شهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (177,'شهرضا','شهرضا',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (178,'طالخونچه','طالخونچه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (179,'عسگران','عسگران',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (180,'علویجه','علویجه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (181,'فرخی','فرخی',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (182,'فریدونشهر','فریدونشهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (183,'فلاورجان','فلاورجان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (184,'فولادشهر','فولادشهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (185,'قمصر','قمصر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (186,'قهجاورستان','قهجاورستان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (187,'قهدریجان','قهدریجان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (188,'کاشان','کاشان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (189,'کرکوند','کرکوند',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (190,'کلیشاد و سودرجان','کلیشاد-سودرجان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (191,'کمشچه','کمشچه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (192,'کمه','کمه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (193,'کهریزسنگ','کهریزسنگ',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (194,'کوشک','کوشک',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (195,'کوهپایه','کوهپایه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (196,'گرگاب','گرگاب',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (197,'گزبرخوار','گزبرخوار',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (198,'گلپایگان','گلپایگان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (199,'گلدشت','گلدشت',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (200,'گلشهر','گلشهر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (201,'گوگد','گوگد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (202,'لای بید','لای-بید',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (203,'مبارکه','مبارکه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (204,'مجلسی','مجلسی',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (205,'محمدآباد','اصفهان-محمدآباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (206,'مشکات','مشکات',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (207,'منظریه','منظریه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (208,'مهاباد','اصفهان-مهاباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (209,'میمه','اصفهان-میمه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (210,'نائین','نائین',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (211,'نجف آباد','نجف-آباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (212,'نصرآباد','اصفهان-نصرآباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (213,'نطنز','نطنز',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (214,'نوش آباد','نوش-آباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (215,'نیاسر','نیاسر',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (216,'نیک آباد','نیک-آباد',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (217,'هرند','هرند',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (218,'ورزنه','ورزنه',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (219,'ورنامخواست','ورنامخواست',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (220,'وزوان','وزوان',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (221,'ونک','ونک',4);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (222,'اسارا','اسارا',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (223,'اشتهارد','اشتهارد',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (224,'تنکمان','تنکمان',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (225,'چهارباغ','چهارباغ',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (226,'سعید آباد','سعید-آباد',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (227,'شهر جدید هشتگرد','شهر-جدید-هشتگرد',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (228,'طالقان','طالقان',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (229,'کرج','کرج',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (230,'کمال شهر','کمال-شهر',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (231,'کوهسار','کوهسار',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (232,'گرمدره','گرمدره',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (233,'ماهدشت','ماهدشت',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (234,'محمدشهر','البرز-محمدشهر',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (235,'مشکین دشت','مشکین-دشت',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (236,'نظرآباد','نظرآباد',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (237,'هشتگرد','هشتگرد',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (238,'ارکواز','ارکواز',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (239,'ایلام','ایلام',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (240,'ایوان','ایوان',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (241,'آبدانان','آبدانان',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (242,'آسمان آباد','آسمان-آباد',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (243,'بدره','بدره',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (244,'پهله','پهله',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (245,'توحید','توحید',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (246,'چوار','چوار',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (247,'دره شهر','دره-شهر',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (248,'دلگشا','دلگشا',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (249,'دهلران','دهلران',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (250,'زرنه','زرنه',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (251,'سراب باغ','سراب-باغ',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (252,'سرابله','سرابله',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (253,'صالح آباد','ایلام-صالح-آباد',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (254,'لومار','لومار',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (255,'مهران','مهران',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (256,'مورموری','مورموری',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (257,'موسیان','موسیان',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (258,'میمه','ایلام-میمه',6);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (259,'امام حسن','امام-حسن',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (260,'انارستان','انارستان',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (261,'اهرم','اهرم',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (262,'آب پخش','آب-پخش',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (263,'آبدان','آبدان',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (264,'برازجان','برازجان',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (265,'بردخون','بردخون',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (266,'بندردیر','بندردیر',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (267,'بندردیلم','بندردیلم',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (268,'بندرریگ','بندرریگ',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (269,'بندرکنگان','بندرکنگان',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (270,'بندرگناوه','بندرگناوه',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (271,'بنک','بنک',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (272,'بوشهر','بوشهر',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (273,'تنگ ارم','تنگ-ارم',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (274,'جم','جم',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (275,'چغادک','چغادک',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (276,'خارک','خارک',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (277,'خورموج','خورموج',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (278,'دالکی','دالکی',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (279,'دلوار','دلوار',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (280,'ریز','ریز',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (281,'سعدآباد','سعدآباد',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (282,'سیراف','سیراف',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (283,'شبانکاره','شبانکاره',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (284,'شنبه','شنبه',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (285,'عسلویه','عسلویه',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (286,'کاکی','کاکی',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (287,'کلمه','کلمه',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (288,'نخل تقی','نخل-تقی',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (289,'وحدتیه','وحدتیه',7);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (290,'ارجمند','ارجمند',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (291,'اسلامشهر','اسلامشهر',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (292,'اندیشه','اندیشه',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (293,'آبسرد','آبسرد',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (294,'آبعلی','آبعلی',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (295,'باغستان','باغستان',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (296,'باقرشهر','باقرشهر',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (297,'بومهن','بومهن',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (298,'پاکدشت','پاکدشت',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (299,'پردیس','پردیس',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (300,'پیشوا','پیشوا',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (301,'تهران','تهران',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (302,'جوادآباد','جوادآباد',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (303,'چهاردانگه','چهاردانگه',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (304,'حسن آباد','تهران-حسن-آباد',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (305,'دماوند','دماوند',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (306,'دیزین','دیزین',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (307,'شهر ری','شهر-ری',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (308,'رباط کریم','رباط-کریم',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (309,'رودهن','رودهن',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (310,'شاهدشهر','شاهدشهر',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (311,'شریف آباد','شریف-آباد',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (312,'شمشک','شمشک',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (313,'شهریار','شهریار',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (314,'صالح آباد','تهران-صالح-آباد',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (315,'صباشهر','صباشهر',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (316,'صفادشت','صفادشت',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (317,'فردوسیه','فردوسیه',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (318,'فشم','فشم',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (319,'فیروزکوه','فیروزکوه',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (320,'قدس','قدس',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (321,'قرچک','قرچک',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (322,'کهریزک','کهریزک',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (323,'کیلان','کیلان',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (324,'گلستان','شهر-گلستان',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (325,'لواسان','لواسان',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (326,'ملارد','ملارد',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (327,'میگون','میگون',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (328,'نسیم شهر','نسیم-شهر',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (329,'نصیرآباد','نصیرآباد',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (330,'وحیدیه','وحیدیه',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (331,'ورامین','ورامین',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (332,'اردل','اردل',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (333,'آلونی','آلونی',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (334,'باباحیدر','باباحیدر',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (335,'بروجن','بروجن',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (336,'بلداجی','بلداجی',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (337,'بن','بن',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (338,'جونقان','جونقان',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (339,'چلگرد','چلگرد',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (340,'سامان','سامان',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (341,'سفیددشت','سفیددشت',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (342,'سودجان','سودجان',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (343,'سورشجان','سورشجان',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (344,'شلمزار','شلمزار',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (345,'شهرکرد','شهرکرد',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (346,'طاقانک','طاقانک',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (347,'فارسان','فارسان',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (348,'فرادنبه','فرادبنه',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (349,'فرخ شهر','فرخ-شهر',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (350,'کیان','کیان',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (351,'گندمان','گندمان',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (352,'گهرو','گهرو',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (353,'لردگان','لردگان',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (354,'مال خلیفه','مال-خلیفه',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (355,'ناغان','ناغان',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (356,'نافچ','نافچ',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (357,'نقنه','نقنه',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (358,'هفشجان','هفشجان',9);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (359,'ارسک','ارسک',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (360,'اسدیه','اسدیه',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (361,'اسفدن','اسفدن',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (362,'اسلامیه','اسلامیه',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (363,'آرین شهر','آرین-شهر',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (364,'آیسک','آیسک',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (365,'بشرویه','بشرویه',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (366,'بیرجند','بیرجند',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (367,'حاجی آباد','خراسان-جنوبی-حاجی-آباد',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (368,'خضری دشت بیاض','خضری-دشت-بیاض',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (369,'خوسف','خوسف',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (370,'زهان','زهان',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (371,'سرایان','سرایان',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (372,'سربیشه','سربیشه',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (373,'سه قلعه','سه-قلعه',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (374,'شوسف','شوسف',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (375,'طبس','خراسان-جنوبی-طبس-',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (376,'فردوس','فردوس',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (377,'قاین','قاین',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (378,'قهستان','قهستان',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (379,'محمدشهر','خراسان-جنوبی-محمدشهر',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (380,'مود','مود',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (381,'نهبندان','نهبندان',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (382,'نیمبلوک','نیمبلوک',10);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (383,'احمدآباد صولت','احمدآباد-صولت',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (384,'انابد','انابد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (385,'باجگیران','باجگیران',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (386,'باخرز','باخرز',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (387,'بار','بار',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (388,'بایگ','بایگ',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (389,'بجستان','بجستان',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (390,'بردسکن','بردسکن',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (391,'بیدخت','بیدخت',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (392,'تایباد','تایباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (393,'تربت جام','تربت-جام',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (394,'تربت حیدریه','تربت-حیدریه',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (395,'جغتای','جغتای',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (396,'جنگل','جنگل',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (397,'چاپشلو','چاپشلو',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (398,'چکنه','چکنه',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (399,'چناران','چناران',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (400,'خرو','خرو',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (401,'خلیل آباد','خلیل-آباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (402,'خواف','خواف',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (403,'داورزن','داورزن',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (404,'درگز','درگز',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (405,'در رود','در-رود',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (406,'دولت آباد','خراسان-رضوی-دولت-آباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (407,'رباط سنگ','رباط-سنگ',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (408,'رشتخوار','رشتخوار',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (409,'رضویه','رضویه',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (410,'روداب','روداب',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (411,'ریوش','ریوش',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (412,'سبزوار','سبزوار',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (413,'سرخس','سرخس',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (414,'سفیدسنگ','سفیدسنگ',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (415,'سلامی','سلامی',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (416,'سلطان آباد','سلطان-آباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (417,'سنگان','سنگان',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (418,'شادمهر','شادمهر',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (419,'شاندیز','شاندیز',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (420,'ششتمد','ششتمد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (421,'شهرآباد','شهرآباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (422,'شهرزو','شهرزو',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (423,'صالح آباد','خراسان-رضوی-صالح-آباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (424,'طرقبه','طرقبه',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (425,'عشق آباد','خراسان-رضوی-عشق-آباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (426,'فرهادگرد','فرهادگرد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (427,'فریمان','فریمان',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (428,'فیروزه','فیروزه',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (429,'فیض آباد','فیض-آباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (430,'قاسم آباد','قاسم-آباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (431,'قدمگاه','قدمگاه',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (432,'قلندرآباد','قلندرآباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (433,'قوچان','قوچان',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (434,'کاخک','کاخک',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (435,'کاریز','کاریز',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (436,'کاشمر','کاشمر',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (437,'کدکن','کدکن',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (438,'کلات','کلات',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (439,'کندر','کندر',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (440,'گلمکان','گلمکان',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (441,'گناباد','گناباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (442,'لطف آباد','لطف-آباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (443,'مزدآوند','مزدآوند',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (444,'مشهد','مشهد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (445,'ملک آباد','ملک-آباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (446,'نشتیفان','نشتیفان',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (447,'نصرآباد','خراسان-رضوی-نصرآباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (448,'نقاب','نقاب',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (449,'نوخندان','نوخندان',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (450,'نیشابور','نیشابور',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (451,'نیل شهر','نیل-شهر',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (452,'همت آباد','همت-آباد',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (453,'یونسی','یونسی',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (454,'اسفراین','اسفراین',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (455,'ایور','ایور',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (456,'آشخانه','آشخانه',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (457,'بجنورد','بجنورد',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (458,'پیش قلعه','پیش-قلعه',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (459,'تیتکانلو','تیتکانلو',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (460,'جاجرم','جاجرم',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (461,'حصارگرمخان','حصارگرمخان',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (462,'درق','درق',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (463,'راز','راز',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (464,'سنخواست','سنخواست',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (465,'شوقان','شوقان',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (466,'شیروان','شیروان',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (467,'صفی آباد','خراسان-شمالی-صفی-آباد',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (468,'فاروج','فاروج',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (469,'قاضی','قاضی',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (470,'گرمه','گرمه',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (471,'لوجلی','لوجلی',12);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (472,'اروندکنار','اروندکنار',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (473,'الوان','الوان',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (474,'امیدیه','امیدیه',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (475,'اندیمشک','اندیمشک',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (476,'اهواز','اهواز',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (477,'ایذه','ایذه',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (478,'آبادان','آبادان',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (479,'آغاجاری','آغاجاری',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (480,'باغ ملک','باغ-ملک',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (481,'بستان','بستان',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (482,'بندرامام خمینی','بندرامام-خمینی',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (483,'بندرماهشهر','بندرماهشهر',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (484,'بهبهان','بهبهان',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (485,'ترکالکی','ترکالکی',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (486,'جایزان','جایزان',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (487,'چمران','چمران',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (488,'چویبده','چویبده',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (489,'حر','حر',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (490,'حسینیه','حسینیه',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (491,'حمزه','حمزه',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (492,'حمیدیه','حمیدیه',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (493,'خرمشهر','خرمشهر',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (494,'دارخوین','دارخوین',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (495,'دزآب','دزآب',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (496,'دزفول','دزفول',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (497,'دهدز','دهدز',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (498,'رامشیر','رامشیر',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (499,'رامهرمز','رامهرمز',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (500,'رفیع','رفیع',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (501,'زهره','زهره',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (502,'سالند','سالند',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (503,'سردشت','خوزستان-سردشت',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (504,'سوسنگرد','سوسنگرد',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (505,'شادگان','شادگان',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (506,'شاوور','شاوور',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (507,'شرافت','شرافت',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (508,'شوش','شوش',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (509,'شوشتر','شوشتر',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (510,'شیبان','شیبان',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (511,'صالح شهر','صالح-شهر',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (512,'صفی آباد','خوزستان-صفی-آباد',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (513,'صیدون','صیدون',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (514,'قلعه تل','قلعه-تل',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (515,'قلعه خواجه','قلعه-خواجه',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (516,'گتوند','گتوند',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (517,'لالی','لالی',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (518,'مسجدسلیمان','مسجدسلیمان',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (520,'ملاثانی','ملاثانی',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (521,'میانرود','میانرود',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (522,'مینوشهر','مینوشهر',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (523,'هفتگل','هفتگل',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (524,'هندیجان','هندیجان',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (525,'هویزه','هویزه',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (526,'ویس','ویس',13);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (527,'ابهر','ابهر',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (528,'ارمغان خانه','ارمغان-خانه',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (529,'آب بر','آب-بر',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (530,'چورزق','چورزق',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (531,'حلب','حلب',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (532,'خرمدره','خرمدره',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (533,'دندی','دندی',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (534,'زرین آباد','زرین-آباد',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (535,'زرین رود','زرین-رود',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (536,'زنجان','زنجان',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (537,'سجاس','سجاس',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (538,'سلطانیه','سلطانیه',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (539,'سهرورد','سهرورد',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (540,'صائین قلعه','صائین-قلعه',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (541,'قیدار','قیدار',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (542,'گرماب','گرماب',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (543,'ماه نشان','ماه-نشان',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (544,'هیدج','هیدج',14);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (545,'امیریه','امیریه',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (546,'ایوانکی','ایوانکی',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (547,'آرادان','آرادان',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (548,'بسطام','بسطام',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (549,'بیارجمند','بیارجمند',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (550,'دامغان','دامغان',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (551,'درجزین','درجزین',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (552,'دیباج','دیباج',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (553,'سرخه','سرخه',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (554,'سمنان','سمنان',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (555,'شاهرود','شاهرود',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (556,'شهمیرزاد','شهمیرزاد',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (557,'کلاته خیج','کلاته-خیج',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (558,'گرمسار','گرمسار',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (559,'مجن','مجن',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (560,'مهدی شهر','مهدی-شهر',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (561,'میامی','میامی',15);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (562,'ادیمی','ادیمی',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (563,'اسپکه','اسپکه',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (564,'ایرانشهر','ایرانشهر',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (565,'بزمان','بزمان',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (566,'بمپور','بمپور',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (567,'بنت','بنت',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (568,'بنجار','بنجار',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (569,'پیشین','پیشین',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (570,'جالق','جالق',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (571,'چابهار','چابهار',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (572,'خاش','خاش',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (573,'دوست محمد','دوست-محمد',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (574,'راسک','راسک',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (575,'زابل','زابل',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (576,'زابلی','زابلی',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (577,'زاهدان','زاهدان',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (578,'زهک','زهک',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (579,'سراوان','سراوان',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (580,'سرباز','سرباز',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (581,'سوران','سوران',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (582,'سیرکان','سیرکان',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (583,'علی اکبر','علی-اکبر',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (584,'فنوج','فنوج',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (585,'قصرقند','قصرقند',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (586,'کنارک','کنارک',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (587,'گشت','گشت',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (588,'گلمورتی','گلمورتی',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (589,'محمدان','محمدان',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (590,'محمدآباد','سیستان-و-بلوچستان-محمدآباد',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (591,'محمدی','محمدی',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (592,'میرجاوه','میرجاوه',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (593,'نصرت آباد','نصرت-آباد',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (594,'نگور','نگور',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (595,'نوک آباد','نوک-آباد',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (596,'نیک شهر','نیک-شهر',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (597,'هیدوچ','هیدوچ',16);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (598,'اردکان','فارس-اردکان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (599,'ارسنجان','ارسنجان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (600,'استهبان','استهبان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (601,'اشکنان','اشکنان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (602,'افزر','افزر',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (603,'اقلید','اقلید',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (604,'امام شهر','امام-شهر',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (605,'اهل','اهل',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (606,'اوز','اوز',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (607,'ایج','ایج',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (608,'ایزدخواست','ایزدخواست',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (609,'آباده','آباده',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (610,'آباده طشک','آباده-طشک',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (611,'باب انار','باب-انار',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (612,'بالاده','فارس-بالاده',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (613,'بنارویه','بنارویه',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (614,'بهمن','بهمن',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (615,'بوانات','بوانات',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (616,'بیرم','بیرم',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (617,'بیضا','بیضا',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (618,'جنت شهر','جنت-شهر',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (619,'جهرم','جهرم',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (620,'جویم','جویم',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (621,'زرین دشت','زرین-دشت',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (622,'حسن آباد','فارس-حسن-آباد',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (623,'خان زنیان','خان-زنیان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (624,'خاوران','خاوران',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (625,'خرامه','خرامه',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (626,'خشت','خشت',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (627,'خنج','خنج',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (628,'خور','فارس-خور',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (629,'داراب','داراب',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (630,'داریان','داریان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (631,'دبیران','دبیران',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (632,'دژکرد','دژکرد',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (633,'دهرم','دهرم',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (634,'دوبرجی','دوبرجی',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (635,'رامجرد','رامجرد',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (636,'رونیز','رونیز',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (637,'زاهدشهر','زاهدشهر',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (638,'زرقان','زرقان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (639,'سده','سده',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (640,'سروستان','سروستان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (641,'سعادت شهر','سعادت-شهر',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (642,'سورمق','سورمق',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (643,'سیدان','سیدان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (644,'ششده','ششده',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (645,'شهرپیر','شهرپیر',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (646,'شهرصدرا','شهرصدرا',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (647,'شیراز','شیراز',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (648,'صغاد','صغاد',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (649,'صفاشهر','صفاشهر',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (650,'علامرودشت','علامرودشت',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (651,'فدامی','فدامی',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (652,'فراشبند','فراشبند',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (653,'فسا','فسا',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (654,'فیروزآباد','فارس-فیروزآباد',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (655,'قائمیه','قائمیه',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (656,'قادرآباد','قادرآباد',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (657,'قطب آباد','قطب-آباد',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (658,'قطرویه','قطرویه',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (659,'قیر','قیر',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (660,'کارزین (فتح آباد)','کارزین-فتح-آباد',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (661,'کازرون','کازرون',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (662,'کامفیروز','کامفیروز',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (663,'کره ای','کره-ای',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (664,'کنارتخته','کنارتخته',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (665,'کوار','کوار',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (666,'گراش','گراش',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (667,'گله دار','گله-دار',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (668,'لار','لار',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (669,'لامرد','لامرد',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (670,'لپویی','لپویی',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (671,'لطیفی','لطیفی',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (672,'مبارک آباددیز','مبارک-آباددیز',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (673,'مرودشت','مرودشت',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (674,'مشکان','مشکان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (675,'مصیری','مصیری',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (676,'مهر','مهر',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (677,'میمند','میمند',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (678,'نوبندگان','نوبندگان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (679,'نوجین','نوجین',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (680,'نودان','نودان',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (681,'نورآباد','فارس-نورآباد',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (682,'نی ریز','نی-ریز',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (683,'وراوی','وراوی',17);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (684,'ارداق','ارداق',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (685,'اسفرورین','اسفرورین',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (686,'اقبالیه','اقبالیه',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (687,'الوند','الوند',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (688,'آبگرم','آبگرم',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (689,'آبیک','آبیک',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (690,'آوج','آوج',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (691,'بوئین زهرا','بوئین-زهرا',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (692,'بیدستان','بیدستان',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (693,'تاکستان','تاکستان',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (694,'خاکعلی','خاکعلی',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (695,'خرمدشت','خرمدشت',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (696,'دانسفهان','دانسفهان',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (697,'رازمیان','رازمیان',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (698,'سگزآباد','سگزآباد',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (699,'سیردان','سیردان',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (700,'شال','شال',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (701,'شریفیه','شریفیه',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (702,'ضیاآباد','ضیاآباد',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (703,'قزوین','قزوین',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (704,'کوهین','کوهین',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (705,'محمدیه','محمدیه',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (706,'محمودآباد نمونه','محمودآباد-نمونه',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (707,'معلم کلایه','معلم-کلایه',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (708,'نرجه','نرجه',18);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (709,'جعفریه','جعفریه',19);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (710,'دستجرد','دستجرد',19);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (711,'سلفچگان','سلفچگان',19);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (712,'قم','قم',19);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (713,'قنوات','قنوات',19);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (714,'کهک','کهک',19);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (715,'آرمرده','آرمرده',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (716,'بابارشانی','بابارشانی',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (717,'بانه','بانه',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (718,'بلبان آباد','بلبان-آباد',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (719,'بوئین سفلی','بوئین-سفلی',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (720,'بیجار','بیجار',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (721,'چناره','چناره',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (722,'دزج','دزج',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (723,'دلبران','دلبران',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (724,'دهگلان','دهگلان',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (725,'دیواندره','دیواندره',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (726,'زرینه','زرینه',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (727,'سروآباد','سروآباد',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (728,'سریش آباد','سریش-آباد',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (729,'سقز','سقز',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (730,'سنندج','سنندج',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (731,'شویشه','شویشه',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (732,'صاحب','صاحب',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (733,'قروه','قروه',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (734,'کامیاران','کامیاران',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (735,'کانی دینار','کانی-دینار',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (736,'کانی سور','کانی-سور',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (737,'مریوان','مریوان',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (738,'موچش','موچش',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (739,'یاسوکند','یاسوکند',20);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (740,'اختیارآباد','اختیارآباد',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (741,'ارزوئیه','ارزوئیه',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (742,'امین شهر','امین-شهر',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (743,'انار','انار',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (744,'اندوهجرد','اندوهجرد',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (745,'باغین','باغین',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (746,'بافت','بافت',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (747,'بردسیر','بردسیر',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (748,'بروات','بروات',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (749,'بزنجان','بزنجان',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (750,'بم','بم',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (751,'بهرمان','بهرمان',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (752,'پاریز','پاریز',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (753,'جبالبارز','جبالبارز',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (754,'جوپار','جوپار',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (755,'جوزم','جوزم',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (756,'جیرفت','جیرفت',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (757,'چترود','چترود',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (758,'خاتون آباد','خاتون-آباد',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (759,'خانوک','خانوک',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (760,'خورسند','خورسند',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (761,'درب بهشت','درب-بهشت',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (762,'دهج','دهج',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (763,'رابر','رابر',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (764,'راور','راور',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (765,'راین','راین',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (766,'رفسنجان','رفسنجان',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (767,'رودبار','کرمان-رودبار',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (768,'ریحان شهر','ریحان-شهر',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (769,'زرند','زرند',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (770,'زنگی آباد','زنگی-آباد',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (771,'زیدآباد','زیدآباد',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (772,'سیرجان','سیرجان',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (773,'شهداد','شهداد',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (774,'شهربابک','شهربابک',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (775,'صفائیه','صفائیه',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (776,'عنبرآباد','عنبرآباد',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (777,'فاریاب','فاریاب',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (778,'فهرج','فهرج',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (779,'قلعه گنج','قلعه-گنج',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (780,'کاظم آباد','کاظم-آباد',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (781,'کرمان','کرمان',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (782,'کشکوئیه','کشکوئیه',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (783,'کهنوج','کهنوج',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (784,'کوهبنان','کوهبنان',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (785,'کیانشهر','کیانشهر',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (786,'گلباف','گلباف',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (787,'گلزار','گلزار',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (788,'لاله زار','لاله-زار',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (789,'ماهان','ماهان',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (790,'محمدآباد','کرمان-محمدآباد',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (791,'محی آباد','محی-آباد',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (792,'مردهک','مردهک',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (793,'مس سرچشمه','مس-سرچشمه',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (794,'منوجان','منوجان',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (795,'نجف شهر','نجف-شهر',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (796,'نرماشیر','نرماشیر',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (797,'نظام شهر','نظام-شهر',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (798,'نگار','نگار',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (799,'نودژ','نودژ',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (800,'هجدک','هجدک',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (801,'یزدان شهر','یزدان-شهر',21);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (802,'ازگله','ازگله',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (803,'اسلام آباد غرب','اسلام-آباد-غرب',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (804,'باینگان','باینگان',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (805,'بیستون','بیستون',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (806,'پاوه','پاوه',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (807,'تازه آباد','تازه-آباد',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (808,'جوان رود','جوان-رود',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (809,'حمیل','حمیل',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (810,'ماهیدشت','ماهیدشت',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (811,'روانسر','روانسر',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (812,'سرپل ذهاب','سرپل-ذهاب',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (813,'سرمست','سرمست',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (814,'سطر','سطر',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (815,'سنقر','سنقر',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (816,'سومار','سومار',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (817,'شاهو','شاهو',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (818,'صحنه','صحنه',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (819,'قصرشیرین','قصرشیرین',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (820,'کرمانشاه','کرمانشاه',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (821,'کرندغرب','کرندغرب',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (822,'کنگاور','کنگاور',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (823,'کوزران','کوزران',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (824,'گهواره','گهواره',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (825,'گیلانغرب','گیلانغرب',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (826,'میان راهان','میان-راهان',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (827,'نودشه','نودشه',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (828,'نوسود','نوسود',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (829,'هرسین','هرسین',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (830,'هلشی','هلشی',22);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (831,'باشت','باشت',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (832,'پاتاوه','پاتاوه',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (833,'چرام','چرام',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (834,'چیتاب','چیتاب',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (835,'دهدشت','دهدشت',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (836,'دوگنبدان','دوگنبدان',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (837,'دیشموک','دیشموک',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (838,'سوق','سوق',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (839,'سی سخت','سی-سخت',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (840,'قلعه رئیسی','قلعه-رئیسی',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (841,'گراب سفلی','گراب-سفلی',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (842,'لنده','لنده',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (843,'لیکک','لیکک',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (844,'مادوان','مادوان',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (845,'مارگون','مارگون',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (846,'یاسوج','یاسوج',23);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (847,'انبارآلوم','انبارآلوم',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (848,'اینچه برون','اینچه-برون',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (849,'آزادشهر','آزادشهر',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (850,'آق قلا','آق-قلا',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (851,'بندرترکمن','بندرترکمن',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (852,'بندرگز','بندرگز',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (853,'جلین','جلین',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (854,'خان ببین','خان-ببین',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (855,'دلند','دلند',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (856,'رامیان','رامیان',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (857,'سرخنکلاته','سرخنکلاته',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (858,'سیمین شهر','سیمین-شهر',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (859,'علی آباد کتول','علی-آباد-کتول',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (860,'فاضل آباد','فاضل-آباد',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (861,'کردکوی','کردکوی',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (862,'کلاله','کلاله',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (863,'گالیکش','گالیکش',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (864,'گرگان','گرگان',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (865,'گمیش تپه','گمیش-تپه',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (866,'گنبدکاووس','گنبدکاووس',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (867,'مراوه','مراوه',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (868,'مینودشت','مینودشت',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (869,'نگین شهر','نگین-شهر',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (870,'نوده خاندوز','نوده-خاندوز',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (871,'نوکنده','نوکنده',24);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (872,'ازنا','ازنا',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (873,'اشترینان','اشترینان',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (874,'الشتر','الشتر',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (875,'الیگودرز','الیگودرز',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (876,'بروجرد','بروجرد',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (877,'پلدختر','پلدختر',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (878,'چالانچولان','چالانچولان',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (879,'چغلوندی','چغلوندی',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (880,'چقابل','چقابل',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (881,'خرم آباد','لرستان-خرم-آباد',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (882,'درب گنبد','درب-گنبد',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (883,'دورود','دورود',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (884,'زاغه','زاغه',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (885,'سپیددشت','سپیددشت',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (886,'سراب دوره','سراب-دوره',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (887,'فیروزآباد','لرستان-فیروزآباد',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (888,'کونانی','کونانی',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (889,'کوهدشت','کوهدشت',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (890,'گراب','گراب',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (891,'معمولان','معمولان',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (892,'مومن آباد','مومن-آباد',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (893,'نورآباد','لرستان-نورآباد',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (894,'ویسیان','ویسیان',25);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (895,'احمدسرگوراب','احمدسرگوراب',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (896,'اسالم','اسالم',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (897,'اطاقور','اطاقور',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (898,'املش','املش',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (899,'آستارا','آستارا',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (900,'آستانه اشرفیه','آستانه-اشرفیه',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (901,'بازار جمعه','بازار-جمعه',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (902,'بره سر','بره-سر',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (903,'بندرانزلی','بندرانزلی',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (906,'پره سر','پره-سر',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (907,'تالش','تالش',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (908,'توتکابن','توتکابن',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (909,'جیرنده','جیرنده',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (910,'چابکسر','چابکسر',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (911,'چاف و چمخاله','چاف-و-چمخاله',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (912,'چوبر','چوبر',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (913,'حویق','حویق',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (914,'خشکبیجار','خشکبیجار',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (915,'خمام','خمام',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (916,'دیلمان','دیلمان',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (917,'رانکوه','رانکوه',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (918,'رحیم آباد','رحیم-آباد',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (919,'رستم آباد','رستم-آباد',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (920,'رشت','رشت',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (921,'رضوانشهر','گیلان-رضوانشهر',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (922,'رودبار','گیلان-رودبار',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (923,'رودبنه','رودبنه',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (924,'رودسر','رودسر',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (925,'سنگر','سنگر',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (926,'سیاهکل','سیاهکل',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (927,'شفت','شفت',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (928,'شلمان','شلمان',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (929,'صومعه سرا','صومعه-سرا',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (930,'فومن','فومن',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (931,'کلاچای','کلاچای',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (932,'کوچصفهان','کوچصفهان',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (933,'کومله','کومله',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (934,'کیاشهر','کیاشهر',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (935,'گوراب زرمیخ','گوراب-زرمیخ',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (936,'لاهیجان','لاهیجان',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (937,'لشت نشا','لشت-نشا',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (938,'لنگرود','لنگرود',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (939,'لوشان','لوشان',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (940,'لولمان','لولمان',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (941,'لوندویل','لوندویل',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (942,'لیسار','لیسار',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (943,'ماسال','ماسال',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (944,'ماسوله','ماسوله',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (945,'مرجقل','مرجقل',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (946,'منجیل','منجیل',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (947,'واجارگاه','واجارگاه',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (948,'امیرکلا','امیرکلا',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (949,'ایزدشهر','ایزدشهر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (950,'آلاشت','آلاشت',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (951,'آمل','آمل',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (952,'بابل','بابل',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (953,'بابلسر','بابلسر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (954,'بلده','مازندران-بلده',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (955,'بهشهر','بهشهر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (956,'بهنمیر','بهنمیر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (957,'پل سفید','پل-سفید',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (958,'تنکابن','تنکابن',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (959,'جویبار','جویبار',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (960,'چالوس','چالوس',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (961,'چمستان','چمستان',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (962,'خرم آباد','مازندران-خرم-آباد',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (963,'خلیل شهر','خلیل-شهر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (964,'خوش رودپی','خوش-رودپی',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (965,'دابودشت','دابودشت',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (966,'رامسر','رامسر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (967,'رستمکلا','رستمکلا',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (968,'رویان','رویان',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (969,'رینه','رینه',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (970,'زرگرمحله','زرگرمحله',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (971,'زیرآب','زیرآب',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (972,'ساری','ساری',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (973,'سرخرود','سرخرود',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (974,'سلمان شهر','سلمان-شهر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (975,'سورک','سورک',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (976,'شیرگاه','شیرگاه',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (977,'شیرود','شیرود',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (978,'عباس آباد','عباس-آباد',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (979,'فریدونکنار','فریدونکنار',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (980,'فریم','فریم',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (981,'قائم شهر','قائم-شهر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (982,'کتالم','کتالم',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (983,'کلارآباد','کلارآباد',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (984,'کلاردشت','کلاردشت',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (985,'کله بست','کله-بست',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (986,'کوهی خیل','کوهی-خیل',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (987,'کیاسر','کیاسر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (988,'کیاکلا','کیاکلا',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (989,'گتاب','گتاب',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (990,'گزنک','گزنک',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (991,'گلوگاه','گلوگاه',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (992,'محمودآباد','مازندران-محمودآباد',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (993,'مرزن آباد','مرزن-آباد',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (994,'مرزیکلا','مرزیکلا',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (995,'نشتارود','نشتارود',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (996,'نکا','نکا',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (997,'نور','نور',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (998,'نوشهر','نوشهر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (999,'اراک','اراک',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1000,'آستانه','آستانه',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1001,'آشتیان','آشتیان',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1002,'پرندک','پرندک',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1003,'تفرش','تفرش',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1004,'توره','توره',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1005,'جاورسیان','جاورسیان',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1006,'خشکرود','خشکرود',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1007,'خمین','خمین',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1008,'خنداب','خنداب',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1009,'داودآباد','داودآباد',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1010,'دلیجان','دلیجان',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1011,'رازقان','رازقان',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1012,'زاویه','زاویه',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1013,'ساروق','ساروق',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1014,'ساوه','ساوه',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1015,'سنجان','سنجان',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1016,'شازند','شازند',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1017,'غرق آباد','غرق-آباد',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1018,'فرمهین','فرمهین',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1019,'قورچی باشی','قورچی-باشی',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1020,'کرهرود','کرهرود',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1021,'کمیجان','کمیجان',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1022,'مامونیه','مامونیه',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1023,'محلات','محلات',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1024,'مهاجران','مهاجران',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1025,'میلاجرد','میلاجرد',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1026,'نراق','نراق',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1027,'نوبران','نوبران',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1028,'نیمور','نیمور',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1029,'هندودر','هندودر',28);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1030,'ابوموسی','ابوموسی',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1031,'بستک','بستک',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1032,'بندرجاسک','بندرجاسک',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1033,'بندرچارک','بندرچارک',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1034,'بندرخمیر','بندرخمیر',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1035,'بندرعباس','بندرعباس',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1036,'بندرلنگه','بندرلنگه',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1037,'بیکا','بیکا',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1038,'پارسیان','پارسیان',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1039,'تخت','تخت',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1040,'جناح','جناح',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1041,'حاجی آباد','هرمزگان-حاجی-آباد',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1042,'درگهان','درگهان',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1043,'دهبارز','دهبارز',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1044,'رویدر','رویدر',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1045,'زیارتعلی','زیارتعلی',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1046,'سردشت','هرمزگان-سردشت',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1047,'سندرک','سندرک',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1048,'سوزا','سوزا',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1049,'سیریک','سیریک',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1050,'فارغان','فارغان',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1051,'فین','فین',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1052,'قشم','قشم',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1053,'قلعه قاضی','قلعه-قاضی',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1054,'کنگ','کنگ',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1055,'کوشکنار','کوشکنار',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1056,'کیش','کیش',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1057,'گوهران','گوهران',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1058,'میناب','میناب',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1059,'هرمز','هرمز',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1060,'هشتبندی','هشتبندی',29);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1061,'ازندریان','ازندریان',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1062,'اسدآباد','اسدآباد',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1063,'برزول','برزول',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1064,'بهار','بهار',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1065,'تویسرکان','تویسرکان',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1066,'جورقان','جورقان',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1067,'جوکار','جوکار',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1068,'دمق','دمق',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1069,'رزن','رزن',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1070,'زنگنه','زنگنه',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1071,'سامن','سامن',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1072,'سرکان','سرکان',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1073,'شیرین سو','شیرین-سو',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1074,'صالح آباد','همدان-صالح-آباد',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1075,'فامنین','فامنین',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1076,'فرسفج','فرسفج',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1077,'فیروزان','فیروزان',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1078,'قروه درجزین','قروه-درجزین',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1079,'قهاوند','قهاوند',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1080,'کبودر آهنگ','کبودر-آهنگ',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1081,'گل تپه','گل-تپه',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1082,'گیان','گیان',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1083,'لالجین','لالجین',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1084,'مریانج','مریانج',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1085,'ملایر','ملایر',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1086,'نهاوند','نهاوند',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1087,'همدان','همدان',30);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1088,'ابرکوه','ابرکوه',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1089,'احمدآباد','احمدآباد',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1090,'اردکان','یزد-اردکان',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1091,'اشکذر','اشکذر',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1092,'بافق','بافق',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1093,'بفروئیه','بفروئیه',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1094,'بهاباد','بهاباد',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1095,'تفت','تفت',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1096,'حمیدیا','حمیدیا',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1097,'خضرآباد','خضرآباد',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1098,'دیهوک','دیهوک',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1099,'زارچ','زارچ',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1100,'شاهدیه','شاهدیه',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1101,'طبس','یزد-طبس',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1103,'عقدا','عقدا',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1104,'مروست','مروست',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1105,'مهردشت','مهردشت',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1106,'مهریز','مهریز',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1107,'میبد','میبد',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1108,'ندوشن','ندوشن',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1109,'نیر','یزد-نیر',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1110,'هرات','هرات',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1111,'یزد','یزد',31);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1116,'پرند','پرند',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1117,'فردیس','فردیس',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1118,'مارلیک','مارلیک',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1119,'سادات شهر','سادات-شهر',27);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1121,'زیباکنار','زیباکنار',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1135,'کردان','کردان',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1137,'ساوجبلاغ','ساوجبلاغ',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1138,'تهران دشت','تهران-دشت',5);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1150,'گلبهار','گلبهار',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1153,'قیامدشت','قیامدشت',8);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1155,'بینالود','بینالود',11);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1159,'پیربازار','پیربازار',26);
     INSERT INTO cities(id,name,slug,"proviceId") VALUES (1160,'رضوانشهر','رضوانشهر',31);
       `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
