import { MigrationInterface, QueryRunner } from "typeorm";

export class ChangeTablesPrimaryId1726658863399 implements MigrationInterface {
    name = 'ChangeTablesPrimaryId1726658863399'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_0cb4a718cc49a5bc41bf4f950e8"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_0b1691cd039bba22ef1c12f538a"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_c6b38625b22af78f04fbf423e74"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_a06a40e89f9347c0f1c7e6834eb"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_425077bcdf46e8832e30f3fcc0f"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "FK_b036bf423c292acb655fe6f93e9"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "FK_d0dd9f6e90ff16c2d4b234b2a01"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP CONSTRAINT "FK_b1712467cdce5b5567e03a34cb3"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP CONSTRAINT "FK_b3af5cda70ec705b57386a69bd2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3af5cda70ec705b57386a69bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1712467cdce5b5567e03a34cb"`);
        await queryRunner.query(`ALTER TABLE "brands" RENAME COLUMN "brandId" TO "id"`);
        await queryRunner.query(`ALTER TABLE "brands" RENAME CONSTRAINT "PK_80bb7c42fb72877053a3b69d020" TO "PK_b0c437120b624da1034a81fc561"`);
        await queryRunner.query(`ALTER SEQUENCE "brands_brandId_seq" RENAME TO "brands_id_seq"`);
        await queryRunner.query(`ALTER TABLE "category" RENAME COLUMN "categoryId" TO "id"`);
        await queryRunner.query(`ALTER TABLE "category" RENAME CONSTRAINT "PK_8a300c5ce0f70ed7945e877a537" TO "PK_9c4e4a89e3674fc9f382d733f03"`);
        await queryRunner.query(`ALTER SEQUENCE "category_categoryId_seq" RENAME TO "category_id_seq"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME COLUMN "userId" TO "id"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME CONSTRAINT "PK_8bf09ba754322ab9c22a215c919" TO "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER SEQUENCE "users_userId_seq" RENAME TO "users_id_seq"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "PK_ff59275f5928941ce06f1d8890c"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "addressId"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "userUserId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "PK_fded04e5e4fb901d8566443e6f1"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "reviewId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "images"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "productProductId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "userUserId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "PK_7b3b507508cd0f86a5b2e923459"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "brandBrandId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "categoryCategoryId"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP COLUMN "orderOrderId"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP COLUMN "productProductId"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "PK_41ba27842ac1a2c24817ca59eaa"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP CONSTRAINT "PK_4337cabb52564d50419af2e61c8"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD CONSTRAINT "PK_b1712467cdce5b5567e03a34cb3" PRIMARY KEY ("productsProductId")`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP COLUMN "usersUserId"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP CONSTRAINT "PK_b1712467cdce5b5567e03a34cb3"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP COLUMN "productsProductId"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "productId" integer`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "products" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "products" ADD "brandId" integer`);
        await queryRunner.query(`ALTER TABLE "products" ADD "categoryId" integer`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD "orderId" integer`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD "productId" integer`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD "usersId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD CONSTRAINT "PK_8aee8ad2a408c631001be82eeb0" PRIMARY KEY ("usersId")`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD "productsId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP CONSTRAINT "PK_8aee8ad2a408c631001be82eeb0"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD CONSTRAINT "PK_40f21f7df7c163f36987fbf1829" PRIMARY KEY ("usersId", "productsId")`);
        await queryRunner.query(`CREATE INDEX "IDX_8aee8ad2a408c631001be82eeb" ON "users_favorites_products" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a08fdd35c8fbc59e57772db28" ON "users_favorites_products" ("productsId") `);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_95c93a584de49f0b0e13f753630" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_a6b3c434392f5d10ec171043666" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df" FOREIGN KEY ("brandId") REFERENCES "brands"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "FK_28b66449cf7cd76444378ad4e92" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "FK_27ca18f2453639a1cafb7404ece" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_710e2d4957aa5878dfe94e4ac2f" FOREIGN KEY ("id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD CONSTRAINT "FK_8aee8ad2a408c631001be82eeb0" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD CONSTRAINT "FK_0a08fdd35c8fbc59e57772db28d" FOREIGN KEY ("productsId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP CONSTRAINT "FK_0a08fdd35c8fbc59e57772db28d"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP CONSTRAINT "FK_8aee8ad2a408c631001be82eeb0"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_710e2d4957aa5878dfe94e4ac2f"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "FK_27ca18f2453639a1cafb7404ece"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "FK_28b66449cf7cd76444378ad4e92"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_a6b3c434392f5d10ec171043666"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_95c93a584de49f0b0e13f753630"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a08fdd35c8fbc59e57772db28"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8aee8ad2a408c631001be82eeb"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP CONSTRAINT "PK_40f21f7df7c163f36987fbf1829"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD CONSTRAINT "PK_8aee8ad2a408c631001be82eeb0" PRIMARY KEY ("usersId")`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP COLUMN "productsId"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP CONSTRAINT "PK_8aee8ad2a408c631001be82eeb0"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP COLUMN "usersId"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "brandId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "PK_231ae565c273ee700b283f15c1d"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "PK_745d8f43d3af10ab8247465e450"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD "productsProductId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD CONSTRAINT "PK_b1712467cdce5b5567e03a34cb3" PRIMARY KEY ("productsProductId")`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD "usersUserId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" DROP CONSTRAINT "PK_b1712467cdce5b5567e03a34cb3"`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD CONSTRAINT "PK_4337cabb52564d50419af2e61c8" PRIMARY KEY ("usersUserId", "productsProductId")`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "orderId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "PK_41ba27842ac1a2c24817ca59eaa" PRIMARY KEY ("orderId")`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD "productProductId" integer`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD "orderOrderId" integer`);
        await queryRunner.query(`ALTER TABLE "products" ADD "categoryCategoryId" integer`);
        await queryRunner.query(`ALTER TABLE "products" ADD "brandBrandId" integer`);
        await queryRunner.query(`ALTER TABLE "products" ADD "productId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "PK_7b3b507508cd0f86a5b2e923459" PRIMARY KEY ("productId")`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "userUserId" integer`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "productProductId" integer`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "images" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "reviewId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "PK_fded04e5e4fb901d8566443e6f1" PRIMARY KEY ("reviewId")`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "userUserId" integer`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "addressId" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "PK_ff59275f5928941ce06f1d8890c" PRIMARY KEY ("addressId")`);
        await queryRunner.query(`ALTER SEQUENCE "users_id_seq" RENAME TO "users_userId_seq"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" TO "PK_8bf09ba754322ab9c22a215c919"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME COLUMN "id" TO "userId"`);
        await queryRunner.query(`ALTER SEQUENCE "category_id_seq" RENAME TO "category_categoryId_seq"`);
        await queryRunner.query(`ALTER TABLE "category" RENAME CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" TO "PK_8a300c5ce0f70ed7945e877a537"`);
        await queryRunner.query(`ALTER TABLE "category" RENAME COLUMN "id" TO "categoryId"`);
        await queryRunner.query(`ALTER SEQUENCE "brands_id_seq" RENAME TO "brands_brandId_seq"`);
        await queryRunner.query(`ALTER TABLE "brands" RENAME CONSTRAINT "PK_b0c437120b624da1034a81fc561" TO "PK_80bb7c42fb72877053a3b69d020"`);
        await queryRunner.query(`ALTER TABLE "brands" RENAME COLUMN "id" TO "brandId"`);
        await queryRunner.query(`CREATE INDEX "IDX_b1712467cdce5b5567e03a34cb" ON "users_favorites_products" ("productsProductId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b3af5cda70ec705b57386a69bd" ON "users_favorites_products" ("usersUserId") `);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD CONSTRAINT "FK_b3af5cda70ec705b57386a69bd2" FOREIGN KEY ("usersUserId") REFERENCES "users"("userId") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_favorites_products" ADD CONSTRAINT "FK_b1712467cdce5b5567e03a34cb3" FOREIGN KEY ("productsProductId") REFERENCES "products"("productId") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "FK_d0dd9f6e90ff16c2d4b234b2a01" FOREIGN KEY ("orderOrderId") REFERENCES "orders"("orderId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "FK_b036bf423c292acb655fe6f93e9" FOREIGN KEY ("productProductId") REFERENCES "products"("productId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_425077bcdf46e8832e30f3fcc0f" FOREIGN KEY ("brandBrandId") REFERENCES "brands"("brandId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_a06a40e89f9347c0f1c7e6834eb" FOREIGN KEY ("categoryCategoryId") REFERENCES "category"("categoryId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_c6b38625b22af78f04fbf423e74" FOREIGN KEY ("productProductId") REFERENCES "products"("productId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_0b1691cd039bba22ef1c12f538a" FOREIGN KEY ("userUserId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_0cb4a718cc49a5bc41bf4f950e8" FOREIGN KEY ("userUserId") REFERENCES "users"("userId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
